// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace ConversionsDb.Migrations
{
    [DbContext(typeof(ConversionsContext))]
    [Migration("20180922035326_SeedDistanceData")]
    partial class SeedDistanceData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ConversionsDb.Models.Units.BaseUnitMap", b =>
                {
                    b.Property<int>("UnitTypeId");

                    b.Property<int>("BaseUnitId");

                    b.HasKey("UnitTypeId", "BaseUnitId");

                    b.HasAlternateKey("BaseUnitId", "UnitTypeId");

                    b.ToTable("BaseUnitMap", "Units");

                    b.HasData(
                        new { UnitTypeId = 1, BaseUnitId = 2 }
                    );
                });

            modelBuilder.Entity("ConversionsDb.Models.Units.RelativeValue", b =>
                {
                    b.Property<int>("BaseUnitId");

                    b.Property<int>("UnitId");

                    b.Property<double>("Value");

                    b.HasKey("BaseUnitId", "UnitId");

                    b.HasIndex("UnitId");

                    b.ToTable("RelativeValue", "Units");

                    b.HasData(
                        new { BaseUnitId = 2, UnitId = 1, Value = 1000.0 },
                        new { BaseUnitId = 2, UnitId = 2, Value = 1.0 },
                        new { BaseUnitId = 2, UnitId = 3, Value = 0.1 },
                        new { BaseUnitId = 2, UnitId = 4, Value = 0.01 },
                        new { BaseUnitId = 2, UnitId = 5, Value = 0.001 },
                        new { BaseUnitId = 2, UnitId = 6, Value = 1e-06 },
                        new { BaseUnitId = 2, UnitId = 7, Value = 1e-09 },
                        new { BaseUnitId = 2, UnitId = 10, Value = 0.3048 },
                        new { BaseUnitId = 10, UnitId = 8, Value = 5280.0 },
                        new { BaseUnitId = 10, UnitId = 9, Value = 3.0 },
                        new { BaseUnitId = 10, UnitId = 10, Value = 1.0 },
                        new { BaseUnitId = 10, UnitId = 11, Value = 0.083333333333333329 },
                        new { BaseUnitId = 10, UnitId = 12, Value = 6076.12 }
                    );
                });

            modelBuilder.Entity("ConversionsDb.Models.Units.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(8);

                    b.HasKey("Id");

                    b.ToTable("Unit", "Units");

                    b.HasData(
                        new { Id = 1, DisplayName = "Kilometre", Symbol = "km" },
                        new { Id = 2, DisplayName = "Metre", Symbol = "m" },
                        new { Id = 3, DisplayName = "Decimetre", Symbol = "dm" },
                        new { Id = 4, DisplayName = "Centimetre", Symbol = "cm" },
                        new { Id = 5, DisplayName = "Millimetre", Symbol = "mm" },
                        new { Id = 6, DisplayName = "Micrometre", Symbol = "μm" },
                        new { Id = 7, DisplayName = "Nanometre", Symbol = "nm" },
                        new { Id = 8, DisplayName = "Mile", Symbol = "mi" },
                        new { Id = 9, DisplayName = "Yard", Symbol = "yd" },
                        new { Id = 10, DisplayName = "Foot", Symbol = "ft" },
                        new { Id = 11, DisplayName = "Inch", Symbol = "in" },
                        new { Id = 12, DisplayName = "NauticalMile", Symbol = "nmi" }
                    );
                });

            modelBuilder.Entity("ConversionsDb.Models.Units.UnitType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.ToTable("UnitType", "Units");

                    b.HasData(
                        new { Id = 1, DisplayName = "Distance" }
                    );
                });

            modelBuilder.Entity("ConversionsDb.Models.Units.UnitTypeMap", b =>
                {
                    b.Property<int>("UnitTypeId");

                    b.Property<int>("UnitId");

                    b.HasKey("UnitTypeId", "UnitId");

                    b.HasAlternateKey("UnitId", "UnitTypeId");

                    b.ToTable("UnitTypeMap", "Units");

                    b.HasData(
                        new { UnitTypeId = 1, UnitId = 1 },
                        new { UnitTypeId = 1, UnitId = 2 },
                        new { UnitTypeId = 1, UnitId = 3 },
                        new { UnitTypeId = 1, UnitId = 4 },
                        new { UnitTypeId = 1, UnitId = 5 },
                        new { UnitTypeId = 1, UnitId = 6 },
                        new { UnitTypeId = 1, UnitId = 7 },
                        new { UnitTypeId = 1, UnitId = 8 },
                        new { UnitTypeId = 1, UnitId = 9 },
                        new { UnitTypeId = 1, UnitId = 10 },
                        new { UnitTypeId = 1, UnitId = 11 },
                        new { UnitTypeId = 1, UnitId = 12 }
                    );
                });

            modelBuilder.Entity("ConversionsDb.Models.Units.BaseUnitMap", b =>
                {
                    b.HasOne("ConversionsDb.Models.Units.Unit", "BaseUnit")
                        .WithMany()
                        .HasForeignKey("BaseUnitId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ConversionsDb.Models.Units.UnitType", "UnitType")
                        .WithMany()
                        .HasForeignKey("UnitTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ConversionsDb.Models.Units.RelativeValue", b =>
                {
                    b.HasOne("ConversionsDb.Models.Units.Unit", "BaseUnit")
                        .WithMany()
                        .HasForeignKey("BaseUnitId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ConversionsDb.Models.Units.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ConversionsDb.Models.Units.UnitTypeMap", b =>
                {
                    b.HasOne("ConversionsDb.Models.Units.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ConversionsDb.Models.Units.UnitType", "UnitType")
                        .WithMany()
                        .HasForeignKey("UnitTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
